# Generated by Django 5.2.4 on 2025-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ManyToManyField(related_name='asignaciones', to='fichas.ficha')),
            ],
        ),
    ]
