# Generated by Django 5.2.4 on 2025-09-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento'), ('en uso', 'En uso'), ('dañado', 'Dañado')], default='disponible', max_length=15)),
                ('ultima_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
