# Generated by Django 5.1.7 on 2025-08-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuario_documento_usuario_face_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('instructor', 'Instructor'), ('seguridad', 'Guardia'), ('aseo', 'Limpieza'), ('inventario', 'Inventario')], default='instructor', max_length=20),
        ),
    ]
