# Generated by Django 5.2.4 on 2025-08-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('aulas', '0001_initial'),
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacion', to='asignaciones.asignacion')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacion', to='aulas.aula')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacion', to='fichas.ficha')),
            ],
        ),
    ]
