# Generated by Django 5.2.4 on 2025-08-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computadores', models.PositiveIntegerField(default=0)),
                ('mouses', models.PositiveIntegerField(default=0)),
                ('teclados', models.PositiveIntegerField(default=0)),
                ('tablets', models.PositiveIntegerField(default=0)),
                ('televisores', models.PositiveIntegerField(default=0)),
                ('proyectores', models.PositiveIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='aulas.aula')),
            ],
        ),
    ]
