# Generated by Django 5.2.4 on 2025-08-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novedades', models.CharField(max_length=255)),
                ('entrada_usuario', models.TimeField()),
                ('salida_usuario', models.TimeField()),
                ('fecha_reporte', models.DateTimeField(auto_now=True)),
                ('programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='programacion.programacion')),
            ],
        ),
    ]
