# Generated by Django 5.1.7 on 2025-08-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiente', '0001_initial'),
        ('fichas', '0003_remove_ficha_programa_ficha_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacion', to='ambiente.ambiente')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacion', to='fichas.ficha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
