# Generated by Django 5.2.4 on 2025-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
    ]
