# Generated by Django 5.2.4 on 2025-09-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_ficha_capacidad_ficha_jornada_ficha_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='programa',
        ),
        migrations.AddField(
            model_name='ficha',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10),
        ),
    ]
