# Generated by Django 5.2.4 on 2025-08-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usuario_email'),
        ('users', '0006_add_emailverificationcode'),
    ]

    operations = [
    ]
