# Generated by Django 5.2.4 on 2025-08-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20250802_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
