# Generated by Django 5.2.4 on 2025-08-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailverificationcode_used'),
    ]

    operations = [
    ]
