# Generated by Django 5.2.4 on 2025-08-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_update_email_verification_code'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='users_email_email_e18436_idx',
            old_name='users_email_email_9c3f4d_idx',
        ),
    ]
