# Generated by Django 5.2.4 on 2025-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=70)),
                ('numero', models.CharField(max_length=8, unique=True)),
                ('jornada', models.CharField(choices=[('diurna', 'Diurna'), ('tarde', 'Tarde'), ('nocturna', 'Nocturna'), ('mixta', 'Mixta')], default='diurna', max_length=15)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
    ]
