# Generated by Django 5.1.7 on 2025-08-14 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('computador', 'Computador'), ('televisor', 'Televisor')], default='computador', max_length=15)),
                ('pulgadas', models.CharField(max_length=5)),
                ('caracteristicas', models.TextField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento'), ('dañado', 'Dañado')], default='disponible', max_length=15)),
                ('ultima_actualizacion', models.DateField(auto_now=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='ambiente.ambiente')),
            ],
        ),
    ]
