# Generated by Django 5.2.4 on 2025-09-03 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_usuario', models.TimeField()),
                ('salida_usuario', models.TimeField()),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('revisado', 'Revisado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=15)),
                ('fecha_reporte', models.DateField(auto_now=True)),
                ('programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='programaciones.programacion')),
            ],
        ),
    ]
