# Generated by Django 5.1.7 on 2025-09-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0001_initial'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='programacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='programaciones.programacion'),
        ),
    ]
